load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "954aa89b491be4a083304a2cb838019c8b8c3720a7abb9c4cb81ac7a24230cea",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.4.0/rules_python-0.4.0.tar.gz",
        "https://github.com/bazelbuild/rules_python/releases/download/0.4.0/rules_python-0.4.0.tar.gz",
    ],
)

local_repository(
    name = "rules_nixpkgs",
    path = "../..",
)

load("@rules_nixpkgs//private:pip_repo.bzl", "nix_pip")

nix_pip(
    name = "npip",
    lock_file = "//:poetry.lock",
    nix_file = "//:default.nix",
    pyproject_file = "//:pyproject.toml",
)

register_toolchains(
    "@npip//:py_toolchain",
)
